= Editors

The first and foremost ingredient of any working environment is editors. Here by editors I means tools to edit files. People have different preferences and different groups of preferences often argue with their choices. Some people prefer IDEs, while other people likes text editors. Some people are GUI oriented [This has nothing to do with IDEs, though.]

== My criteria for editors

For me, editors are simply editors. I use editors to accomplish text editing part of the work. So my criteria for editors comes as follows:

1. Speed: how fast and convenient can I process text in them.
2. Availability: is the editor available on all platforms I use? Can I deploy it easily if not?
3. Extensibility: since my needs changes overtime, I need it to be extensible to cope with new needs.

The above criteria excludes most of the current IDEs. IDEs do some part of programming work efficiently but fail both on availability and extensibility. Among IDEs I tried, I want to discuss Eclipse and QtCreator. 

=== About Eclipse

Eclipse is a comprehensive platform. It's omnipotent. By install the CDT plugin, it can be used as a C/C++ IDE. By installing the Egit plugin, It's integrated with git version control. One can even install plugins to make it manage computing clusters and do parallel computing.

The problem of Eclipse in my case is that It needs GUIs to function. So not avaliable on any of my clusters. It's also slow to start due to heavy JAVA dependency. JAVA availability used to be a problem but now we have OpenJDK on almost every Linux distribution. It does not support the edit-compile-run-edit programming cycle efficiently due to its slow startup.

So, although Eclipse is a nice platform, I pass over it.

=== About QtCreator

QtCreator is a nimble IDE. It's mainly focused on C/C++ projects and is fast compared to Eclipse. It does not use JAVA but compiled directly to machine code. It has modern IDE capabilities such as syntax highlighting, semantic completion, source code navigation and refactoring. It's fully functional.

The problem of QtCreator is that it's not extensible. Although it has some kind of plugin system, it has a much smaller user community as of Eclipse. You can not edit fortran, markdown, json files efficiently with it. So I passed it over. However, I will use it when contributing to Qt based projects.

=== Comments on IDEs

I do not choose IDE as a major component of my working environment. But I use IDEs to accomplish certain development tasks. This may seem paradoxical but is justified. I make my choice on a practical manner. Some tasks are better handled by IDEs, for example, GUI applications in QT, debugging QT applications, etc. By I *do not* try to expert on that. I merely use the default configuration, the default plugin set. The IDE itself is efficient enough on the task it focused on, So I don't take the trouble to make it more efficient.

== My choice of Editors

I choose vim as my major editor and considering use Atom for a modern GUI-based editor. They satisfy the above criteria of editors.

Questions here may be the vim-emacs editor war. I used to be an Emacs user and use emacs daily for coding and my Ph.D thesis. It suits my needs well. Emacs is an advanced editor which is even refered to as _An operation system faked as an editor_. This is true in some sense. Emacs focus on fast editing as well as extensibility. I stick to emacs for quite a long time until I encountered the cluster environment. The cluster is shipped with a low version emacs (no emacs daemon support), it's not easy to install a new one. The real problem is that advanced features of emacs rely on modern versions of emacs. This requires a lot of efforts. Most of the times, I simply use editors as editors. vim is avaliable almost everywhere and it's fast. It has built in support for fast editing and it loads fast. So I switched back to vim. The decision brings me speed of editing as well as new power of vim. vim is extremely extensible and can do a lot if shipped with plugins. The nice part is that there are a lot of plugin managers for vim to make it easy and trivial to install.

I also look into Atom. At the beginning, I want to find a more modern editor, which supports fast GUI based editing as vim does for TUI based editing. Sublime Text comes into my eye. I have to say sublime text impressed me significantly. It focused on fast editing, extensible and fast to load. It provides a new style of GUI editing by making good use of GUI to display more information and be focused, such as minimap, fuzzy finder. It lets me know the first time that GUI-based editors can be versitile and swift. However, sublime text is neither opensource nor freeware. It evolves slowly (sublime text 3.0 is still in beta at the time of writing). Then GitHub releases atom, which resembles the sublime way of editing and is opensource. The Atom community grows fast after the first release of the editor. It's extremely extensible and usable. I did not switch to Atom, though. Atom takes another approach to editing, it's pretty and nifty. But I still need the console to edit a lot of files on clusters. So I am not going to shift. Instead, I try Atom occasionally, and may use it regularly when some plugins mature.



